always_trailing_comma = false
multiline_trailing_comma = true

max_array_line_len = 80
indent_count = 4
crlf = false
trailing_newline = true
allowed_blank_lines = 1

space_around_eq = true
compact_arrays = false
compact_inline_tables = false
key_value_newlines = true

# The user specified ordering of tables in a document.
# All unspecified tables will come after these.
table_order = [ "package", "profile" ]
