name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: ⌛ Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: "clippy, rustfmt"
      - uses: Swatinem/rust-cache@v2
      - name: ⏰ Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: 🔨 Build
        run: cargo build --locked

      - name: 🔎 Check formatting
        run: cargo fmt --check
      - name: 🔎 Lint
        run: cargo clippy --workspace --all-targets --no-deps --frozen -- -D warnings
      - name: 🔎 Check Cargo.toml
        run: cargo install cargo-sort && cargo sort -g -c

      - name: 🧪 Run tests
        run: cargo test --no-fail-fast --locked
